#clusetr config
spring:
  application:
    name:ha-eukara-server

#register to eureka server
eureka:
  client:
    register-with-eureka:false

#get register info, default is true 
eureka:
  client:
    fetch-registry:false

#cluster1
spring:
  profiles:eurekaServer2
#port
server:
  port:8001
#eureka
eureka:
  instance:
    hostname:eurekaServer2
  client:
    serviceUrl:
	  #register to eurekaServer1
      defaultZone: http://eurekaServer1:8000/eureka